name: Auto Add Posts

on:
  push:
    branches:
      - main
    paths:
      - new_posts/** # Trigger only on changes to the new_posts directory

jobs:
  process-markdown:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Process Markdown
        run: |
          mkdir -p _posts
          for file in new_posts/*.md; do
            date=$(date +%Y-%m-%d)
            title=$(basename "$file" .md | tr ' ' '-')
            post="_posts/${date}-${title}.md"
            echo "---" > $post
            echo "title: $(basename $file .md)" >> $post
            echo "date: $(date +%Y-%m-%dT%H:%M:%S)" >> $post
            echo "categories: [General]" >> $post
            echo "tags: []" >> $post
            echo "---" >> $post
            cat $file >> $post
          done

      - name: Delete Contents of new_posts
        run: |
          find new_posts -type f -delete

      - name: Push changes
        run: |
          git config --global user.name "TehilaTheStudent"
          git config --global user.email "tehila14916@gmail.com"
          git add _posts/ new_posts/
          git commit -m "Add new posts from new_posts directory and clean up"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
